const skins = [

{
champion: "Tachi",
name: "Acheron",
label: "#Honkai: Star Rail | 9thg1",
Android: "https://link4m.com/lLh2D0",                                 IOS: "https://link4m.com/NRDWW",
bgImg: "img/acheron.png",
miniImg: "img/acheron_mini.png",
videoPreview: "video/acheron.mp4",
desc: "Effects - Sound - Button",
color: "145, 130, 225",
},
{
champion: "Tulen",
name: "DanHeng IL",
label: "#Honkai: Star Rail | 6thg1",
Android: "https://link4m.com/WCg84SO6",                               IOS: "https://link4m.com/NGAIqt4k",
bgImg: "img/danheng.png",
miniImg: "img/danheng_mini.png",
videoPreview: "video/danhengil.mp4",
desc: "Effects - Sound",
color: "70, 255, 225",
},
{
champion: "Violet",
name: "Carlotta",
label: "#Wuthering Waves | 5thg1",
Android: "https://link4m.com/FaoKfA5",                                IOS: "https://link4m.com/K5esN8",
bgImg: "img/carlotta.png",
miniImg: "img/carlotta_mini.png",
videoPreview: "video/carlotta.mp4",
desc: "Effects - Sound - Button",
color: "255, 100, 160",
},
{
champion: "Mina",
name: "Arlecchino",
label: "#Genshin Impact | 4thg1",
Android: "https://link4m.com/lqBu2",                                  IOS: "https://link4m.com/4RKK5",
bgImg: "img/arlecchino.png",
miniImg: "img/arlecchino_mini.png",
videoPreview: "video/arlecchino.mp4",
desc: "Effects - Sound - Button",
color: "255, 100, 100",
},
{
champion: "Allain",
name: "Lạc Tuyết Bạch Lang",
label: "#Honor of King | 3thg1",
Android: "https://link4m.com/aV5Wp",                                  IOS: "https://link4m.com/388Gk",
bgImg: "img/53703v2.png",
miniImg: "img/53703v2_mini.png",
videoPreview: "video/53703v2.mp4",
desc: "Effects - Sound - Button - Notify",
color: "150, 222, 255",
},
{
champion: "Richter",
name: "Eugeo",
label: "#SAO: Alicization | 1thg1",
Android: "https://link4m.com/nw7nBEa",                                IOS: "https://link4m.com/O1Iun9dz",
bgImg: "img/eugeo.png",
miniImg: "img/eugeo_mini.png",
videoPreview: "video/eugeo.mp4",
desc: "Effects - Sound",
color: "100, 225, 255",
},
{
champion: "Amily",
name: "Sparkle",
label: "#Honkai: Star Rail | 31thg12",
Android: "https://link4m.com/jWei0TtL",                               IOS: "https://link4m.com/FJL9Hx",
bgImg: "img/sparkle.png",
miniImg: "img/sparkle_mini.png",
videoPreview: "video/sparkle.mp4",
desc: "Effects - Sound",
color: "225, 25, 100",
},
{
champion: "Butterfly",
name: "Castorice",
label: "#Honkai: Star Rail | 29thg12",
Android: "https://link4m.com/RNiAZEx",                                IOS: "https://link4m.com/JoG1lp",
bgImg: "img/castorice.png",
miniImg: "img/castorice_mini.png",
videoPreview: "video/castorice.mp4",
desc: "Effects - Sound - Button",
color: "225, 170, 255",
},
{
champion: "Florentino",
name: "Blade",
label: "#Honkai: Star Rail | 29thg12",
Android: "https://link4m.com/L6Oeo",                                  IOS: "https://link4m.com/TDsE1MA",
bgImg: "img/blade.png",
miniImg: "img/blade_mini.png",
videoPreview: "video/blade.mp4",
desc: "Effects - Sound - Button",
color: "255, 70, 70",
},
{
champion: "Allain",
name: "Firefly",
label: "#Honkai: Star Rail | 29thg12",
Android: "https://link4m.com/tBHxFZ",                                 IOS: "https://link4m.com/KqSWzP",
bgImg: "img/firefly.png",
miniImg: "img/firefly_mini.png",
videoPreview: "video/firefly.mp4",
desc: "Effects - Sound - Button - Notify",
color: "60, 255, 180",
},
{
champion: "Allain",
name: "Feixiao",
label: "#Honkai: Star Rail | 29thg12",
Android: "https://link4m.com/wuqfEAC",
IOS: "https://link4m.com/fBxBIWbs",
bgImg: "img/feixiao.png",
miniImg: "img/feixiao_mini.png",
videoPreview: "video/feixiao.mp4",
desc: "Effects - Sound - Button - Notify",
color: "100, 255, 225",
},
{
champion: "Butterfly",
name: "Cartethyia",
label: "#Wuthering Waves | 26thg12",
Android: "https://link4m.com/HxkBBqf",                                IOS: "https://link4m.com/GpJ6R2",
bgImg: "img/cartethyia.png",
miniImg: "img/cartethyia_head.png",
videoPreview: "video/cartethyia.mp4",
desc: "Effects - Sound - Button",
color: "100, 180, 225",
},
{
champion: "Nakroth",
name: "Xiao",
label: "#Genshin Impact | 25thg12",
Android: "https://link4m.com/ug6ahi",                                 IOS: "https://link4m.com/7SduU",
bgImg: "img/xiao.png",
miniImg: "img/xiao_mini.png",
videoPreview: "video/xiao.mp4",
desc: "Effects - Sound - Button",
color: "100, 255, 225",
},
{
champion: "Bright",
name: "Kaslana",
label: "#Honkai: Star Rail | 24thg12",
Android: "https://link4m.com/QY98s",                                  IOS: "https://link4m.com/jHmyN",
bgImg: "img/kaslana.png",
miniImg: "img/kaslana_mini.png",
videoPreview: "video/kaslana.mp4",
desc: "Effects - Sound - Button",
color: "255, 220, 40",
},
{
champion: "Triệu Vân",
name: "DanHeng PT",
label: "#Honkai: Star Rail | 24thg12",
Android: "https://link4m.com/qW0Xm9D",                                IOS: "https://link4m.com/UJb54v",
bgImg: "img/danhengpt.png",
miniImg: "img/danhengpt_mini.png",
videoPreview: "video/danhengpt.mp4",
desc: "Effects - Sound - Button - Notify",
color: "255, 200, 120",
},
{
champion: "Butterfly",
name: "Changli",
label: "#Wuthering Waves | 24thg12",
Android: "https://link4m.com/TNHT99",                                 IOS: "https://link4m.com/MD3LSye",
bgImg: "img/changli.png",
miniImg: "img/changli_mini.png",
videoPreview: "video/changli.mp4",
desc: "Effects - Sound - Button",
color: "255, 190, 150",
},
{
champion: "Volkath",
name: "Mavuika",
label: "#Genshin Impact | 23thg12",
Android: "https://link4m.com/hgTi7mI",                                IOS: "https://link4m.com/2ln7LN",
bgImg: "img/mavuika.png",
miniImg: "img/mavuika_mini.png",
videoPreview: "video/mavuika.mp4",
desc: "Effects - Sound - Button",
color: "255, 150, 100",
},
{
champion: "Biron",
name: "Mydei",
label: "#Honkai: Star Rail | 23thg12",
Android: "https://link4m.com/Inz12D",                                 IOS: "https://link4m.com/aYw1Fsc9",
bgImg: "img/mydei.png",
miniImg: "img/mydei_mini.png",
videoPreview: "video/mydei.mp4",
desc: "Effects - Sound - Button",
color: "255, 100, 100",
},
{
champion: "Florentino",
name: "Furina",
label: "#Genshin Impact | 23thg12",
Android: "https://link4m.com/vyGB3tr",                                IOS: "https://link4m.com/Qv5lDyb",
bgImg: "img/furina.png",
miniImg: "img/furina_mini.png",
videoPreview: "video/furina.mp4",
desc: "Effects - Sound - Button",
color: "60, 160, 255",
},
{
champion: "Airi",
name: "Skirk",
label: "#Genshin Impact | 23thg12",
Android: "https://link4m.com/yfzVxh",                                 IOS: "https://link4m.com/qEraXj",
bgImg: "img/skirk.png",
miniImg: "img/skirk_mini.png",
videoPreview: "video/skirk.mp4",
desc: "Effects - Sound - Button",
color: "222, 222, 255",
},
{
champion: "Wiro",
name: "Mặc định",
label: "Cài 1 lần, dùng đến khi game sập",
Android: "https://link4m.com/HP8hrEE",
IOS: "https://link4m.com/HP8hrEE",
bgImg: "img/19400.jpg",
miniImg: "img/301940head.jpg",
desc: "Effects - Sound - Button - Notify",
color: "255, 200, 50",
}
];