const skins = [
{
champion: "Bright",
name: "Kaslana",
label: "#Honkai: Star Rail | 24thg12",
Android: "https://link4m.com/QY98s",                                  IOS: "https://link4m.com/jHmyN",
bgImg: "img/kaslana.png",
miniImg: "img/kaslana_mini.png",
desc: "Effects - Sound - Button",
color: "255, 220, 40",
},
{
champion: "Triệu Vân",
name: "DanHeng PT",
label: "#Honkai: Star Rail | 24thg12",
Android: "https://link4m.com/qW0Xm9D",                                IOS: "https://link4m.com/UJb54v",
bgImg: "img/danhengpt.png",
miniImg: "img/danhengpt_mini.png",
desc: "Effects - Sound - Button - Notify",
color: "255, 200, 120",
},
{
champion: "Butterfly",
name: "Changli",
label: "#Wuthering Waves | 24thg12",
Android: "https://link4m.com/TNHT99",                                 IOS: "https://link4m.com/MD3LSye",
bgImg: "img/changli.png",
miniImg: "img/changli_mini.png",
desc: "Effects - Sound - Button",
color: "255, 190, 150",
},
{
champion: "Volkath",
name: "Mavuika",
label: "#Genshin Impact | 23thg12",
Android: "https://link4m.com/hgTi7mI",                                IOS: "https://link4m.com/2ln7LN",
bgImg: "img/mavuika.png",
miniImg: "img/mavuika_mini.png",
desc: "Effects - Sound - Button",
color: "255, 150, 100",
},
{
champion: "Biron",
name: "Mydei",
label: "#Honkai: Star Rail | 23thg12",
Android: "https://link4m.com/Inz12D",                                 IOS: "https://link4m.com/aYw1Fsc9",
bgImg: "img/mydei.png",
miniImg: "img/mydei_mini.png",
desc: "Effects - Sound - Button",
color: "255, 100, 100",
},
{
champion: "Florentino",
name: "Furina",
label: "#Genshin Impact | 23thg12",
Android: "https://link4m.com/vyGB3tr",                                IOS: "https://link4m.com/Qv5lDyb",
bgImg: "img/furina.png",
miniImg: "img/furina_mini.png",
desc: "Effects - Sound - Button",
color: "60, 160, 255",
},
{
champion: "Airi",
name: "Skirk",
label: "#Genshin Impact | 23thg12",
Android: "https://link4m.com/yfzVxh",                                 IOS: "https://link4m.com/qEraXj",
bgImg: "img/skirk.png",
miniImg: "img/skirk_mini.png",
desc: "Effects - Sound - Button",
color: "222, 222, 255",
},
{
champion: "Wiro",
name: "Mặc định",
label: "Cài 1 lần, dùng đến khi game sập",
Android: "https://link4m.com/HP8hrEE",
IOS: "https://link4m.com/HP8hrEE",
bgImg: "img/19400.jpg",
miniImg: "img/301940head.jpg",
desc: "Effects - Sound - Button - Notify",
color: "255, 200, 50",
}
];